const ACTION_TYPES = {
  GET_ALL_PROYECTS: "GET_ALL_PROYECTS",
  GET_PROYECT_NAME: "GET_PROYECT_NAME",
  CREATE_PROYECT: "CREATE_PROYECT",
  DELETE_PROYECT_SUCCESS: "DELETE_PROYECT_SUCCESS",
  DELETE_PROYECT_FAILURE: "DELETE_PROYECT_FAILURE",
  MODIFY_PROYECT_SUCCESS: "MODIFY_PROYECT_SUCCESS",
  MODIFY_PROYECT_FAILURE: "MODIFY_PROYECT_FAILURE",
  GET_ALL_AUTHORS: "GET_ALL_AUTHORS",
  CREATE_AUTHOR: "CREATE_AUTHOR",
  DELETE_AUTHOR_SUCCESS: "DELETE_AUTHOR_SUCCESS",
  DELETE_AUTHOR_FAILURE:"DELETE_AUTHOR_FAILURE",
  ERROR:"ERROR",
  
}
    
export default ACTION_TYPES;